config/routes.rb
Alternah8::Application.routes.draw do
  get "welcome/index"
  devise_for :users
  resources :alternatives

  resources :companies

  root 'welcome#index'

end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
  belongs_to :company
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :company
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :alternatives, dependent: :destroy
	validates_presence_of :name

	def to_s
		name
	end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :alternative
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/alternatives_controller.rb
class AlternativesController < ApplicationController
  before_action :set_alternative, only: [:show, :edit, :update, :destroy]

  # GET /alternatives
  # GET /alternatives.json
  def index
    @alternatives = Alternative.all
  end

  # GET /alternatives/1
  # GET /alternatives/1.json
  def show
  end

  # GET /alternatives/new
  def new
    @alternative = Alternative.new
  end

  # GET /alternatives/1/edit
  def edit
  end

  # POST /alternatives
  # POST /alternatives.json
  def create
    @alternative = Alternative.new(alternative_params)

    respond_to do |format|
      if @alternative.save
        format.html { redirect_to @alternative, notice: 'Alternative was successfully created.' }
        format.json { render action: 'show', status: :created, location: @alternative }
      else
        format.html { render action: 'new' }
        format.json { render json: @alternative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alternatives/1
  # PATCH/PUT /alternatives/1.json
  def update
    respond_to do |format|
      if @alternative.update(alternative_params)
        format.html { redirect_to @alternative, notice: "Alternative was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @alternative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alternatives/1
  # DELETE /alternatives/1.json
  def destroy
    @alternative.destroy
    respond_to do |format|
      format.html { redirect_to alternatives_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alternative
      @alternative = Alternative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alternative_params
      params.require(:alternative).permit(:name, :description, :company_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
    @groups = @companies.in_groups_of( (@companies.size/2.0).ceil, false ) if @companies.size > 0
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :hrc_score, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/alternatives_helper.rb
module AlternativesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/alternatives/_form.html.erb
<%= form_for(@alternative) do |f| %>
  <% if @alternative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alternative.errors.count, "error") %> prohibited this alternative from being saved:</h2>

      <ul>
      <% @alternative.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= collection_select(:alternative, :company_id, Company.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alternatives/edit.html.erb
<h1>Editing alternative</h1>

<%= render 'form' %>

<%= link_to 'Show', @alternative %> |
<%= link_to 'Back', alternatives_path %>

app/views/alternatives/index.html.erb
<h1>Listing alternatives</h1>
<div class="col-md-4">
  <% @alternatives.each do |alternative| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="pull-right">HRC Score: <%= alternative.hrc_score %></div>
        <%= alternative.name %>
      </div>
      <div class="panel-body">
        <%= alternative.description %>
      </div>
      <div class="panel-footer">
        Alternative to: <%= link_to alternative.company.name, alternative.company %>
      </div>
    </div>
  <% end %>
</div>

app/views/alternatives/new.html.erb
<h1>New alternative</h1>

<%= render 'form' %>

<%= link_to 'Back', alternatives_path %>

app/views/alternatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @alternative.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @alternative.description %>
</p>

<p>
  <strong>Company:</strong>
  <%= @alternative.company %>
</p>

<%= link_to 'Edit', edit_alternative_path(@alternative) %> |
<%= link_to 'Back', alternatives_path %>

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :hrc_score %><br>
    <%= f.number_field :hrc_score %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>
<% @groups.each do |group| %>
  <div class="col-md-4">
    <% group.each do |company| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= company.name %>
        </div>
        <div class="panel-body">
          <%= company.description %>
        </div>
        <div class="panel-footer">
          HRC Score: <%= company.hrc_score %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Hrc score:</strong>
  <%= @company.hrc_score %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-fixed-top header">
    <div class="col-md-12">
        <div class="navbar-header">
            <%= link_to 'Alternah8', root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= render 'layouts/user_widget' %>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/_user_widget.html.erb
<% if user_signed_in? %>
    Welcome <%= current_user.email %>
<% else %>
    You are not signed in
    <%= link_to 'Login', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alternah8</title>
  <%= stylesheet_link_tag    "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "styles", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery-2.1.3", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "scripts", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <%= render 'layouts/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="col-md-4 col-sm-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>
                Welcome to Alternah8
            </h4>
        </div>
        <div class="panel-body">
            Alternah8 is a new site dedicated to finding alternatives to companies with low HRC scores.
        </div>
    </div>
</div>